backend:
  name: github
  repo: lovepreet-singh123/decamps  # Your GitHub repo
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  site_domain: flana-dhimkana.netlify.app
  auth_endpoint: auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
