backend:
    name: git-gateway
    branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
    - name: "achievements"
      label: "Achievements"
      folder: "content/achievements"
      create: true
      fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "image", label: "Image", widget: "image" }
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "body", label: "Body", widget: "markdown" }
          
    - name: "faqs"
      label: "Faqs"
      folder: "content/faqs"
      create: true
      fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "body", label: "Body", widget: "markdown" }

    - name: "blogs"
      label: "Blogs"
      folder: "content/blogs"
      create: true
      slug: "{{slug}}"
      fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "image", label: "Image", widget: "image" }
          - { name: "token_image", label: "Token Image", widget: "image" }
          - {
                name: "isActive",
                label: "Status",
                widget: "select",
                options: ["active", "blocked"],
                default: "active",
            }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "tags", label: "Tags", widget: "list", separator: "," }
          - { name: "minInvestment",label: "Minimum Investment($)",widget: "number",}
          - { name: "projectYield",label: "Project Yield(%)",widget: "number",}
          - { name: "nav",label: "NAV($)",widget: "number",}
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "endDate", label: "End Date", widget: "datetime" }
          - { name: "body", label: "Body", widget: "markdown" }
